### ISSUE TITLE
Hello, where is the dataset? Can you give me a web address?

### ISSUE THREAD

**Issue by 847001315** [qahathaway/Cardiac_Remodeling_Radiomics#1]
Hi, your work is really great, I would like to know in this article, i.e. : Ultrasonic Texture Features for Assessing Cardiac Remodeling and Dysfunction, where is the data set? Is it open source? Can you provide the download source?

**Comment by qahathaway** [comment]
Hi 847001315,

Unfortunately the dataset is not open source...Though, the primary semantic segmentation algorithm is (Circulation
. 2018 Oct 16;138(16):1623-1635. doi: 10.1161/CIRCULATIONAHA.118.034338). If you are looking for an open-source alternative, try: EchoNet-Dynamic (https://echonet.github.io/dynamic/).

Thanks,

Quincy
